"""gh CLI wrapper. Idempotent open_pr (checks for existing head-branch PR).
auto_merge calls open + `gh pr merge --auto --squash`.

Per spec §3 + §5.3 (error tiers; auth failure halts daemon)."""
from __future__ import annotations

import asyncio
import json
from dataclasses import dataclass
from typing import Literal

from pm_agent.scanner import Finding


PRAction = Literal["opened", "auto-merge-queued", "merged-now", "failed"]


@dataclass
class PRResult:
    number: int
    url: str
    action: PRAction


@dataclass
class PRState:
    number: int
    state: Literal["open", "merged", "closed"]
    head_ref: str
    merged_at: str | None


class GhAuthError(RuntimeError):
    """Raised when gh CLI reports authentication failure. Daemon halts."""


_AUTH_MARKERS = (
    "authentication",
    "gh auth login",
    "bad credentials",
    "401",
    "unauthorized",
    "credentials",
    "no authentication token",
)


def _is_auth_failure(stderr: str) -> bool:
    """gh signals auth failure via varied stderr messages depending on version
    and error type. We err on the side of broader matching — daemon halt is
    preferable to looping forever against an unauthenticated gh."""
    s = stderr.lower()
    return any(m in s for m in _AUTH_MARKERS)


async def _gh(*args: str) -> tuple[int, str, str]:
    """Call gh with args; return (returncode, stdout, stderr).

    Raises GhAuthError when gh reports authentication failure — caller (loop.py)
    should halt the daemon and surface this prominently in the dashboard.

    Wraps communicate() in asyncio.wait_for(timeout=30s) so a hung gh
    (stale credential prompt / network timeout) does not block the daemon's
    event loop indefinitely.

    stdin is pinned to DEVNULL: if gh ever decides to prompt (rare interactive
    flows like `pr merge` without --yes, or `pr create` with missing fields)
    and the daemon was launched from a TTY, the subprocess would otherwise
    inherit our stdin and block until the 30s timeout. DEVNULL makes any
    such prompt return EOF immediately, surfacing as a clean non-zero exit.
    """
    proc = await asyncio.create_subprocess_exec(
        "gh", *args,
        stdin=asyncio.subprocess.DEVNULL,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    try:
        out, err = await asyncio.wait_for(proc.communicate(), timeout=30.0)
    except asyncio.TimeoutError:
        try:
            proc.terminate()
            await asyncio.wait_for(proc.wait(), timeout=2.0)
        except (ProcessLookupError, asyncio.TimeoutError):
            try:
                proc.kill()
            except ProcessLookupError:
                pass
        return 124, "", "gh timeout after 30s"
    stdout = out.decode("utf-8", errors="replace") if out else ""
    stderr = err.decode("utf-8", errors="replace") if err else ""
    assert proc.returncode is not None, "communicate() must set returncode"
    rc = proc.returncode
    if rc != 0 and _is_auth_failure(stderr):
        raise GhAuthError(f"gh auth failure: {stderr.strip()[:200]}")
    return rc, stdout, stderr


def _build_pr_body(finding: Finding, body_extras: str = "") -> str:
    acc = "\n".join(f"- {a}" for a in finding.acceptance)
    body = (
        f"**Auto-generated by pm-agent loop**\n\n"
        f"Bug ID: `{finding.bug_id}` · Severity: **{finding.severity}** · Kind: {finding.kind}\n\n"
        f"**Evidence:** {finding.evidence}\n\n"
        f"**Acceptance criteria:**\n{acc}\n"
    )
    if body_extras:
        body += f"\n---\n\n**Pre-merge gate output (failed):**\n```\n{body_extras[:2000]}\n```\n"
    return body


async def _find_existing_pr(branch: str) -> dict | None:
    """Return first OPEN PR with given head ref, or None.

    Filtered to --state open: a closed PR on the same branch is not a hit;
    we want to know if there's a live PR we can reuse (idempotency).
    """
    rc, out, _err = await _gh(
        "pr", "list", "--head", branch, "--state", "open",
        "--json", "number,url,state", "--limit", "1",
    )
    if rc != 0 or not out.strip():
        return None
    try:
        rows = json.loads(out)
        return rows[0] if rows else None
    except json.JSONDecodeError:
        return None


async def open_pr(branch: str, finding: Finding, body_extras: str = "") -> PRResult:
    """Idempotent. Checks for existing PR on `branch` head first; returns it if any.
    Otherwise creates new with title `[severity] title` and structured body."""
    existing = await _find_existing_pr(branch)
    if existing:
        return PRResult(number=existing["number"], url=existing["url"], action="opened")
    rc, out, _err = await _gh(
        "pr", "create",
        "--head", branch,
        "--title", f"[{finding.severity}] {finding.title}",
        "--body", _build_pr_body(finding, body_extras),
    )
    if rc != 0:
        return PRResult(number=0, url="", action="failed")
    # gh pr create may return JSON (with --json) or plain URL on stdout.
    # Our shim returns JSON via the 'pr create' key, but real gh prints URL.
    try:
        data = json.loads(out)
        return PRResult(number=data["number"], url=data["url"], action="opened")
    except (json.JSONDecodeError, KeyError):
        # Fallback for plain URL output
        url = out.strip().splitlines()[-1] if out.strip() else ""
        try:
            num = int(url.rsplit("/", 1)[-1]) if url else 0
        except ValueError:
            num = 0
        return PRResult(number=num, url=url, action="opened")


async def auto_merge(branch: str, finding: Finding) -> PRResult:
    """open_pr + gh pr merge --auto --squash. action reflects merge state.

    Distinguishes 'auto-merge-queued' (waiting on CI / branch protection)
    from 'merged-now' (gh applied the merge immediately). gh's queued message
    contains 'will be automatically merged ...' which would otherwise match
    the naive 'merged' substring — check queued markers first.
    """
    pr = await open_pr(branch, finding)
    if pr.action == "failed":
        return pr
    rc, out, err = await _gh(
        "pr", "merge", str(pr.number), "--auto", "--squash", "--yes",
    )
    if rc != 0:
        # gh returns non-zero with "auto-merge is already enabled" stderr when
        # a previous queue for this PR is still valid — that's not a failure,
        # the auto-merge state we wanted is already in place.
        err_l = err.lower()
        if "already enabled" in err_l or "auto-merge enabled" in err_l:
            return PRResult(number=pr.number, url=pr.url, action="auto-merge-queued")
        return PRResult(number=pr.number, url=pr.url, action="failed")
    out_l = out.lower()
    queued = any(marker in out_l for marker in (
        "automatically merged",
        "will be merged",
        "set to merge",  # older gh phrasing
        "queued",
        "already enabled",  # covers stdout variant of "auto-merge is already enabled"
    ))
    action: PRAction = "auto-merge-queued" if queued else "merged-now"
    return PRResult(number=pr.number, url=pr.url, action=action)


async def sync_pr_states() -> list[PRState]:
    """gh pr list --state all --search 'head:ai/' → list of PRState.
    Maps GH's uppercase state strings (MERGED/CLOSED/OPEN) to our lowercase."""
    rc, out, _err = await _gh(
        "pr", "list", "--state", "all",
        "--search", "head:ai/",
        "--json", "number,state,headRefName,mergedAt",
        "--limit", "200",
    )
    if rc != 0 or not out.strip():
        return []
    try:
        rows = json.loads(out)
    except json.JSONDecodeError:
        return []
    states: list[PRState] = []
    for r in rows:
        gh_state = r.get("state", "").upper()
        if gh_state == "MERGED":
            s = "merged"
        elif gh_state == "CLOSED":
            s = "closed"
        else:
            s = "open"
        states.append(PRState(
            number=r["number"],
            state=s,  # type: ignore[arg-type]
            head_ref=r.get("headRefName", ""),
            merged_at=r.get("mergedAt"),
        ))
    return states
